export const HEADER = {
  MOBILE_HEIGHT: 64,
  MAIN_DESKTOP_HEIGHT: 88,
  DESKTOP_HEIGHT: 92,
  DESKTOP_OFFSET_HEIGHT: 92 - 32,
}

export const NAVBAR = {
  MAIN_NAVBAR_WIDTH: 88,
  SECONDARY_NAVBAR_WIDTH: 280,
  MAIN_NAVBAR_WIDTH_MOBILE: 300,
  SECONDARY_NAVBAR_COLLAPSE_WIDTH: 88,
}
